### ISSUE TITLE
Discussion: Should we keep or remove Groups on LDC.org ckan site?

### ISSUE THREAD

**Issue by ajdrake** [ajdrake/louisvilledatacommons#25]
I asked Ted if we need groups, and his respond was a question about how are Orgs and Groups different. As far as I know, Groups are collection of datasets, and Orgs are actual entities that are either for profit business, schools, institutions, etc. 

If we can articulate how to use groups on the site, then we should us this feature to its potential. However, if we think it will lead to confusion, and incorrect usage, then perhaps we remove it from the site for now. What do you think @parkerduff

**Comment by parkerduff** [comment]
Let’s leave them for the time being an attempt to use them, but if it gets confusing we can go back and remove them later

**Comment by ajdrake** [comment]
sounds good
