### ISSUE TITLE
Improve on-site data integrations with extensions

### ISSUE THREAD

**Issue by parkerduff** [ajdrake/louisvilledatacommons#26]
**Activate your CKAN virtualenv:**
source /usr/lib/ckan/bin/activate
**Install ckanext-sitemap:**
pip install -e git://github.com/kata-csc/ckanext-sitemap.git#egg=ckanext-sitemap
**Install its dependencies (you will also need the libxml2 and libxslt C libraries):**
pip install -r /usr/lib/ckan/src/ckanext-sitemap/requirements.txt
**Add ckanext-sitemap to your CKAN configuration file (e.g. /etc/ckan/production.ini):**
ckan.plugins = ... sitemap
**Finally, restart CKAN:**
sudo service apache2 restart

First extension to install should be sitemap

https://extensions.ckan.org/extension/sitemap/

ran these steps
https://github.com/kata-csc/ckanext-sitemap

**Comment by ajdrake** [comment]
@parkerduff do you have a link from the maintainers guide on how to add extensions. What geo/mapping extensions come with the ckan instance we borrowed from ckan-vagrant ? Perhaps there is something we can already use that is already installed.

**Comment by parkerduff** [comment]
https://docs.ckan.org/en/2.8/extensions/tutorial.html

There is a whole lot of documentation on this, and I'm still not sure how to exactly install one.

**Comment by parkerduff** [comment]
With the CKAN setup are also bootstrapped and configured the following CKAN extensions and plugins:

DataStore
DataPusher
FileStore
Resource Proxy
Spatial Extension

[https://gitlab.com/sciamlab/ckan-vagrant]:(https://gitlab.com/sciamlab/ckan-vagrant)

**Comment by parkerduff** [comment]
https://gitlab.com/sciamlab/ckan-vagrant

**Comment by ajdrake** [comment]
Investigate how to visualize the smell my city map on a automated daily basis, and connect with Paul on how to they generate their map.

**Comment by parkerduff** [comment]
Possibly helpful extensions:

Comment Extensions:
https://extensions.ckan.org/extension/ytp-comments/
https://extensions.ckan.org/extension/wpcomments/

Workflow extensions:
**https://extensions.ckan.org/extension/customuserprivileges/**
**https://extensions.ckan.org/extension/userautoadd/**
https://extensions.ckan.org/extension/review/
https://extensions.ckan.org/extension/resourceauthorizer/
https://extensions.ckan.org/extension/privatedatasets/
https://extensions.ckan.org/extension/ytp-request/


Other:
https://extensions.ckan.org/extension/basiccharts/
https://extensions.ckan.org/extension/ckan-upload/
https://extensions.ckan.org/extension/datarequests/
https://extensions.ckan.org/extension/spatialui/
https://extensions.ckan.org/extension/spatial/
https://extensions.ckan.org/extension/importlib/
https://extensions.ckan.org/extension/datajson/


Note: 
**It seems to me that we will have to make an organization called "submissions" and make the default upload private with only the admin able to make it public. When it is approved it can go into the public data organization**

**Comment by ajdrake** [comment]
sitemap extension has been applied, which created this xml file for search engines

http://louisvilledatacommons.org/sitemap.xml

production.ini now looks like this...
ckan.plugins = text_view image_view recline_view datastore sitemap
@parkerduff

**Comment by ajdrake** [comment]
<img width="753" alt="Screen Shot 2019-08-13 at 10 17 08 PM" src="https://user-images.githubusercontent.com/1540701/62989956-1dcd5800-be18-11e9-82ec-49c4d4f8fa9c.png">
@parkerduff google results look more reasonable now
