### ISSUE TITLE
Combine with WordPress site for better user experience

### ISSUE THREAD

**Issue by ajdrake** [ajdrake/louisvilledatacommons#36]
https://www.youtube.com/watch?v=4WR7EFFLF04

WordPress as the main domain and the CKAN site as the subdomain

add a "submit a community concern" section to the site
add a "data stories" section to the site

http://34.195.14.246

**Comment by parkerduff** [comment]
Email From other people who did this: Checked in with our developers, and basically, they didn’t do anything fancy for this.  They reimplemented our header from the home page in our ckan theme (mainly a lot of copy and paste).  You can find the theme here: https://github.com/UCSUR-Pitt/ckanext-wprdctheme/tree/new-style.
