### ISSUE TITLE
iNaturalist worksheet for students

### ISSUE THREAD

**Issue by parkerduff** [ajdrake/louisvilledatacommons#64]
What content do we want on the worksheet?
What grade level and age group? Anyone should be able to do it.
Identifications (i.e. leaves, insects)
Paragraph on photosenthesis, etc.

https://www.inaturalist.org/pages/teacher's+guide

https://www.inaturalist.org/pages/video+tutorials

https://www.inaturalist.org/pages/video+tutorials#add_web

Two sheets
(1) with access to inaturalist
(2) w/out access to inaturalist

Zoe + Cindy to work on spanish translation
Nur to do the Turkish translation

Worksheet questions
(1) How many cardinals do you see in your back yard and what dates?
(2) Birds, bugs, bats, rabbits

[elementary/middle]

LDC aggregates data recordings
need an email option

https://docs.google.com/document/d/1OgyatF6Hf8gjdRQJX9bM7KQskmTsAH7ziUGkk8WbPFY/edit

**Comment by ajdrake** [comment]
Would be nice to see Louisville on the city nature challenge 2021 

https://www.inaturalist.org/projects/city-nature-challenge-2020

**Comment by ajdrake** [comment]
https://github.com/ajdrake/LouisvilleDataCommons/raw/master/projects/nature/Nature%20Program%20Bird%20Checklist.xlsx
